#ifndef TIMESCALES_H
#define TIMESCALES_H

// TLM TIMESCALES
#define VP_CYCLE_TIME 500 // ns
#define VP_TQ_TIME 5000
// AMS TIMESCALES
#define AMS_MODEL_TIMESTEP 1000.0 // us

// PERIPHERAL TIMESCALES
#define VP_SENSOR_SAMPLING_TIME 5 // ms

#endif // TIMESCALES_H
